# Generated by Django 3.1.3 on 2022-01-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20220102_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinfo',
            name='lect_grade',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
