# Generated by Django 3.1.3 on 2022-01-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20220107_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureinfo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_name', to='lecture.teacher'),
        ),
    ]
