# Generated by Django 3.1.3 on 2022-01-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_teacher_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinfo',
            name='in_cnt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
