# Generated by Django 3.1.3 on 2022-01-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_lectureinfo_in_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinfo',
            name='timeselect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='lect_fee_explan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='lect_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='lect_yoil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
