# Generated by Django 3.1.3 on 2022-01-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_auto_20220109_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinfo',
            name='lect_time2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='lect_time',
            field=models.CharField(db_column='lect_time', blank=True, max_length=255, null=True),
        ),
    ]
