# Generated by Django 3.1.3 on 2022-01-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0009_lectureinfo_lect_time2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureinfo',
            name='lect_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),


    ]
