# Generated by Django 3.1.3 on 2022-01-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0010_auto_20220109_1327'),
    ]


