# Generated by Django 3.1.3 on 2022-01-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0011_auto_20220109_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureinfo',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='season_nm',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
