# Generated by Django 3.1.3 on 2022-01-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0012_auto_20220110_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_nm', models.CharField(max_length=255)),
                ('num', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_nm', models.CharField(max_length=255)),
                ('num', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
