# Generated by Django 3.1.3 on 2022-01-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0013_campus_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjects',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
