# Generated by Django 3.1.3 on 2022-01-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0014_auto_20220112_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_nm', models.CharField(max_length=255)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
