# Generated by Django 3.1.3 on 2022-01-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0016_lectureinfo_science'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_nm', models.CharField(max_length=255)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
