# Generated by Django 3.1.3 on 2022-02-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0017_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='yoil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoil_nm', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
