# Generated by Django 3.1.3 on 2022-03-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0019_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinfo',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
