# Generated by Django 3.1.3 on 2022-03-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0020_lectureinfo_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinfo',
            name='lect_bigo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
