# Generated by Django 4.0.3 on 2023-08-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0021_lectureinfo_lect_bigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureinfo',
            name='name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
