# Generated by Django 3.1.3 on 2021-12-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gitenstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameis', models.CharField(max_length=50)),
                ('schoolis', models.CharField(max_length=100)),
                ('gradeis', models.CharField(max_length=50)),
                ('phoneis', models.CharField(max_length=200)),
                ('bboosamis', models.CharField(max_length=50)),
                ('emailis', models.CharField(max_length=200)),
                ('monthis', models.CharField(max_length=50)),
                ('firstweek', models.CharField(max_length=100)),
                ('secondtweek', models.CharField(max_length=100)),
                ('thirdtweekone', models.CharField(max_length=100)),
                ('thirdtweektwo', models.CharField(max_length=100)),
                ('fourthweek', models.CharField(max_length=100)),
            ],
        ),
    ]
