# Generated by Django 3.1.3 on 2021-12-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitenstudent',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gitenstudent',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitenstudent',
            name='emailis',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
