# Generated by Django 3.1.3 on 2021-12-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giten', '0002_auto_20211228_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitenstudent',
            old_name='secondtweek',
            new_name='secondweek',
        ),
        migrations.RenameField(
            model_name='gitenstudent',
            old_name='thirdtweekone',
            new_name='thirdweekone',
        ),
        migrations.RenameField(
            model_name='gitenstudent',
            old_name='thirdtweektwo',
            new_name='thirdweektwo',
        ),
    ]
