# Generated by Django 3.1.3 on 2021-12-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giten', '0003_auto_20211228_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitenstudent',
            name='campis',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
