# Generated by Django 3.1.3 on 2021-12-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giten', '0005_auto_20211229_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitenstudent',
            name='emailis',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
